---
title: "Etat Recaptulatif de la Collecte de ce jour: `r Sys.Date()`"
author: "Komlan Samati"
format:
  pdf:
    pdf-engine: lualatex
---

# I. Nombre de questionnaires remplis par enquêteur

Le graphique ci-dessous retrace le nombre de questionnaires remplis par chaque enquêteurs.

```{r}
#| label: graph
#| warning: false
#| message: false
#| echo: false


library(knitr)
library(tidyverse)
library(tibble)
library(gt)
readRDS('survey_data.rds') |>
    select(3:7) -> df

df %>% 
  labelled::remove_val_labels() %>%
  summarise(nombre = n(),.by=enqu_teur) %>%
  ungroup %>%
  add_row( enqu_teur = 'Moyenne', !!! colMeans(.[-1])) %>%
  mutate(sup_moy = ifelse(enqu_teur == "Moyenne", TRUE, FALSE)) %>% 
  mutate(enqu_teur = fct_reorder(enqu_teur, nombre)) %>% 
  ggplot(aes(x=enqu_teur,y=nombre,fill=sup_moy)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(name=NULL, values = c("#B0B0B0D0", "#00B0F0"))+
  coord_flip() +
  theme_minimal() +
  theme(axis.title.x=element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(size = 8.5),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_blank()
       )

 
```



# II. Les questionnaires avec les valeures manquantes

Le tableau ci-dessous donne les valeurs manquantes des questionnaires. Les enquêteurs sont invités à vérifier ces informations et à les complèter.

```{r}
#| label: tab1
#| warning: false
#| message: false
#| echo: false
#| results: "asis"

df |>
  labelled::remove_val_labels() |>
  filter(is.na(lieu_d_habitation) | is.na(entrer_votre_localisation)) |>
  gt::gt() |>
  tab_spanner(
    label = md("**Les questionnaires à complèter**"),
    columns = c(2:5)
  ) %>%
   fmt_number(
    columns = 5,
    decimals = 3
  ) %>%
  cols_label(
    `enqu_teur` = "Nom enquêteur",
    `sexe` = "Sexe",
    `age` = "Age",
    `lieu_d_habitation` = "Lieu de residence",
    `entrer_votre_localisation` = "Geolocalisation"
  ) %>%
 cols_align(align = "center",
             columns = 2:5)

```



