on:
  schedule:
    - cron: '5 * * * *'

jobs:
  import-data:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::robotoolbox
            any::janitor

      - name: Import data
        run: Rscript -e 'source("import_data.R")'
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN_GHA }}
          MY_UID: ${{ secrets.MY_UID_GHA }}
          MY_USER: ${{ secrets.MY_USER_GHA }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD}}

      - name: Commit results
        run: |
          git config --local user.email "kn.samati@gmail.com"
          git config --local user.name "knsamati"
          git add survey_data.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"